# 门户 Demo → 10.20.201.215:13000
location /app-web/ {
    proxy_pass http://10.20.201.215:13000/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /app-web;
    proxy_redirect http://10.20.201.215:13000/ /app-web/;
    proxy_redirect http://10.20.201.215:13000 /app-web;
}
