# AI开放平台（研发环境）
# 配置域名: http(s)://apidev.vnet.com  ->  原域名: https://apidev.apifox.cn
server {
    listen 80;
    listen 443 ssl;
    server_name apidev.vnet.com;

    ssl_certificate /etc/nginx/certs/open.vnet.com.pem;
    ssl_certificate_key /etc/nginx/certs/open.vnet.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://5475790.n3.apifox.cn;
        
        # Apifox 自有服务器中转必需的头信息
        proxy_set_header X-Apifox-Docs-Site-ID 5475790;
        proxy_set_header Original-Host  apivnet.apifox.cn;
        
        # 强制 Host 头部为上游域名
        # proxy_set_header Host 5475790.n3.apifox.cn;
    }
}
