# AI开放平台（内部）
# 配置域名: http(s)://api.vnet.com  ->  原域名: https://apivnet.apifox.cn
server {
    listen 80;
    listen 443 ssl;
    server_name api.vnet.com;

    ssl_certificate /etc/nginx/certs/open.vnet.com.pem;
    ssl_certificate_key /etc/nginx/certs/open.vnet.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
<<<<<<< HEAD
        proxy_pass https://apivnet.apifox.cn;

        # 强制 Host 头部为上游域名
        proxy_set_header Host apivnet.apifox.cn;

=======
        proxy_pass https://5492741.n3.apifox.cn;
        
        # Apifox 自有服务器中转必需的头信息
        proxy_set_header X-Apifox-Docs-Site-ID 5492741;
        proxy_set_header Original-Host  apivnet.apifox.cn;
        
        # 强制 Host 头部为上游域名
        # proxy_set_header Host 5492741.n3.apifox.cn;
        
>>>>>>> 28367f9 (update)
        # 其它常规代理头
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
